filenames:
  - /var/log/caddy/*.log
labels:
  type: caddy
---
source: docker
container_name:
 - immich_server
labels:
  type: immich
---
filenames:
  - /var/log/authelia/*
labels:
  type: authelia
---
